[build]
 publish = "."
 command = "npm run build"

# Netlify CMS 관리자 리다이렉트 설정
[[redirects]]
 from = "/admin/*"
 to = "/admin/index.html"
 status = 200

# Netlify Identity 설정
[template.environment]
 NETLIFY_IDENTITY_WIDGET_ON = "true"

# 메모리 제한 설정 추가
[build.environment]
 NODE_OPTIONS = "--max_old_space_size=4096"
 NODE_VERSION = "16.20.2"
 NPM_VERSION = "8.19.4"